---
abstract: 'Perl extension for PKCS#11'
author:
  - 'Markus Lauer, E<lt>mlarue@cpan.orgE<gt>'
build_requires:
  Crypt::OpenSSL::Bignum: '0'
  Crypt::OpenSSL::RSA: '0'
  Devel::PPPort: '0'
  ExtUtils::CBuilder: '0'
  ExtUtils::Constant: '0'
  ExtUtils::ParseXS: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crypt-Cryptoki
provides:
  Crypt::Cryptoki:
    file: lib/Crypt/Cryptoki.pm
    version: 0.01_07
  Crypt::Cryptoki::Constant:
    file: lib/Crypt/Cryptoki/Constant.pm
  Crypt::Cryptoki::Key:
    file: lib/Crypt/Cryptoki/Key.pm
  Crypt::Cryptoki::Object:
    file: lib/Crypt/Cryptoki/Object.pm
  Crypt::Cryptoki::PrivateKey:
    file: lib/Crypt/Cryptoki/PrivateKey.pm
  Crypt::Cryptoki::PublicKey:
    file: lib/Crypt/Cryptoki/PublicKey.pm
  Crypt::Cryptoki::Raw:
    file: lib/Crypt/Cryptoki/Raw.pm
  Crypt::Cryptoki::Session:
    file: lib/Crypt/Cryptoki/Session.pm
  Crypt::Cryptoki::Slot:
    file: lib/Crypt/Cryptoki/Slot.pm
  Crypt::Cryptoki::SlotWithToken:
    file: lib/Crypt/Cryptoki/SlotWithToken.pm
  Crypt::Cryptoki::Template:
    file: lib/Crypt/Cryptoki/Template.pm
  Crypt::Cryptoki::Template::Key:
    file: lib/Crypt/Cryptoki/Template/Key.pm
  Crypt::Cryptoki::Template::PrivateKey:
    file: lib/Crypt/Cryptoki/Template/PrivateKey.pm
  Crypt::Cryptoki::Template::PublicKey:
    file: lib/Crypt/Cryptoki/Template/PublicKey.pm
  Crypt::Cryptoki::Template::RSAPrivateKey:
    file: lib/Crypt/Cryptoki/Template/RSAPrivateKey.pm
  Crypt::Cryptoki::Template::RSAPublicKey:
    file: lib/Crypt/Cryptoki/Template/RSAPublicKey.pm
  Crypt::Cryptoki::Template::Storage:
    file: lib/Crypt/Cryptoki/Template/Storage.pm
requires:
  perl: v5.14.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_07
